### ISSUE TITLE
download link broken

### ISSUE THREAD

**Issue by dudebing99** [nebulasio/nebdocs#147]
```code
root@7bfb2b17e40a:/opt# wget http://ory7cn4fx.bkt.clouddn.com/vendor.tar.gz
--2019-04-24 06:24:21--  http://ory7cn4fx.bkt.clouddn.com/vendor.tar.gz
Resolving ory7cn4fx.bkt.clouddn.com (ory7cn4fx.bkt.clouddn.com)... 121.9.246.109, 121.9.246.110, 121.9.246.105, ...
Connecting to ory7cn4fx.bkt.clouddn.com (ory7cn4fx.bkt.clouddn.com)|121.9.246.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-24 06:24:21 ERROR 404: Not Found.
```

**Comment by newyear6565** [comment]
you can try this :
http://develop-center.oss-cn-zhangjiakou.aliyuncs.com/setup/vendor/vendor.tar.gz

**Comment by dudebing99** [comment]
Thanks. 
Another question, can I compile nebulas from source code on Ubuntu 14.04?

**Comment by newyear6565** [comment]
you can follow this guidance
http://wiki.nebulas.io/en/latest/go-nebulas/tutorials/01-installation.html#compile-nebulas

**Comment by dudebing99** [comment]
> you can follow this guidance
> http://wiki.nebulas.io/en/latest/go-nebulas/tutorials/01-installation.html#compile-nebulas

Actually, I've tried to follow the guidance and some unexpected errors happened.
I do not see any tips showing supported ubuntu versions. I just want to make sure. Thanks.

**Comment by newyear6565** [comment]
please create a new issue and paste your error logs on it, maybe other people have encountered the problem
