### ISSUE TITLE
2018-12-3 404 link report

### ISSUE THREAD

**Issue by 1c7** [nebulasio/nebdocs#32]
![image](https://user-images.githubusercontent.com/1804755/49368474-be1b9a80-f729-11e8-8ef2-63cd83a89105.png)
https://nebulas.io/docs/NebulasTechnicalWhitePaper.pdf

![image](https://user-images.githubusercontent.com/1804755/49368487-c542a880-f729-11e8-934c-2c5aa610964b.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/49368505-cffd3d80-f729-11e8-8c3c-38b5645aab85.png)
https://wiki.nebulas.io/en/latest/overview.html
![image](https://user-images.githubusercontent.com/1804755/49368514-d4c1f180-f729-11e8-8327-56003403b85f.png)

**Comment by weiht12** [comment]
报告～bug已经修复完毕～，欢迎小伙伴跟我们一起编辑wiki哈。
Report ~ bug has been fixed ~, welcome friends to edit wiki with us. @1c7
